# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='name',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
