# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prefix_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LittleWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('type', models.CharField(choices=[('pr', 'Preposition'), ('cn', 'Conjuction'), ('fr', 'Fraction')], max_length=2)),
            ],
        ),
    ]
