# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_littleword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=63)),
                ('is_error', models.BooleanField(default=False)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.End')),
            ],
        ),
        migrations.CreateModel(
            name='NGramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProbUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_value', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='main.NGramm')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='main.NGramm')),
            ],
        ),
        migrations.AddField(
            model_name='full',
            name='grams',
            field=models.ManyToManyField(to='main.NGramm'),
        ),
        migrations.AddField(
            model_name='full',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Main'),
        ),
        migrations.AddField(
            model_name='full',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Prefix'),
        ),
    ]
