# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161211_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full',
            name='grams',
        ),
        migrations.AddField(
            model_name='main',
            name='grams',
            field=models.ManyToManyField(to='main.NGramm'),
        ),
    ]
