# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161211_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full',
            name='end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.End'),
        ),
        migrations.AlterField(
            model_name='full',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Prefix'),
        ),
    ]
