# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170301_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=5)),
                ('answer', models.CharField(max_length=5)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
