# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
